# Generated by Django 3.1.7 on 2021-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_schoolperiod_section_subject_yearlevel'),
        ('students', '0003_student_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, null=True, to='main.Subject'),
        ),
    ]
