# Generated by Django 3.1.7 on 2021-08-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_auto_20210814_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adviser',
            field=models.ForeignKey(default=82, limit_choices_to=models.Q(is_teacher=True), on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
            preserve_default=False,
        ),
    ]
