# Generated by Django 3.1.7 on 2021-08-14 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20210814_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='LRN_or_student_number',
            field=models.CharField(default=13213216, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
