# Generated by Django 3.1.7 on 2021-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(default='sample address'),
            preserve_default=False,
        ),
    ]
