# Generated by Django 3.1.7 on 2021-08-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20210814_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adviser',
        ),
    ]
