# Generated by Django 3.1.7 on 2021-07-09 08:07

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollogo',
            name='ext',
            field=models.CharField(default='png', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoollogo',
            name='image',
            field=models.ImageField(upload_to=cms.models.UploadToPathAndRename),
        ),
    ]
