# Generated by Django 3.1.7 on 2021-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210709_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollogo',
            name='image',
            field=models.ImageField(upload_to='school_logo'),
        ),
    ]
