# Generated by Django 3.1.7 on 2021-07-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210709_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoollogo',
            name='ext',
        ),
    ]
