# Generated by Django 3.1.7 on 2021-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210709_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='homecarousel')),
                ('label', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='schoollogo',
            options={'verbose_name_plural': 'School Logo'},
        ),
    ]
