# Generated by Django 3.1.7 on 2021-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20210713_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Mission',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Vision',
            },
        ),
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'verbose_name_plural': 'Home Page Carousel'},
        ),
    ]
