# Generated by Django 3.1.7 on 2021-07-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210722_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vision',
            name='vision',
            field=models.TextField(max_length=1000),
        ),
    ]
