# Generated by Django 3.1.7 on 2021-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210722_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBesideMissionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='Mission and Vision pic')),
            ],
        ),
    ]
