# Generated by Django 3.1.7 on 2021-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20210723_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteheaderimage',
            options={'verbose_name_plural': 'Site Header Image'},
        ),
        migrations.AddField(
            model_name='siteheaderimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
