# Generated by Django 3.1.7 on 2021-08-07 08:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210723_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
