# Generated by Django 3.1.7 on 2021-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20210807_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=55)),
                ('town', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('province', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolContactNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_day', models.CharField(choices=[('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], default='Monday', max_length=12)),
                ('last_day', models.CharField(choices=[('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], default='Friday', max_length=12)),
                ('opening', models.CharField(choices=[('12NN', '12NN'), ('7AM', '7AM'), ('4PM', '4PM'), ('9AM', '9AM'), ('10AM', '10AM'), ('3PM', '3PM'), ('5PM', '5PM'), ('6AM', '6AM'), ('7PM', '7PM'), ('1PM', '1PM'), ('8PM', '8PM'), ('6PM', '6PM'), ('2PM', '2PM'), ('9PM', '9PM'), ('8AM', '8AM'), ('11AM', '11AM')], default='8AM', max_length=4)),
                ('closing', models.CharField(choices=[('12NN', '12NN'), ('7AM', '7AM'), ('4PM', '4PM'), ('9AM', '9AM'), ('10AM', '10AM'), ('3PM', '3PM'), ('5PM', '5PM'), ('6AM', '6AM'), ('7PM', '7PM'), ('1PM', '1PM'), ('8PM', '8PM'), ('6PM', '6PM'), ('2PM', '2PM'), ('9PM', '9PM'), ('8AM', '8AM'), ('11AM', '11AM')], default='5PM', max_length=4)),
            ],
        ),
    ]
