# Generated by Django 3.1.7 on 2021-08-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20210808_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladdress',
            options={'verbose_name_plural': 'School Address'},
        ),
        migrations.AlterModelOptions(
            name='schoolcontactnumbers',
            options={'verbose_name_plural': 'Contact Numbers'},
        ),
        migrations.AlterModelOptions(
            name='schoolofficehours',
            options={'verbose_name_plural': 'School Office Hours'},
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.CharField(choices=[('6PM', '6PM'), ('1PM', '1PM'), ('2PM', '2PM'), ('7AM', '7AM'), ('11AM', '11AM'), ('10AM', '10AM'), ('12NN', '12NN'), ('4PM', '4PM'), ('7PM', '7PM'), ('3PM', '3PM'), ('8PM', '8PM'), ('6AM', '6AM'), ('9PM', '9PM'), ('8AM', '8AM'), ('5PM', '5PM'), ('9AM', '9AM')], default='5PM', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Monday', 'Monday')], default='Friday', max_length=12),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.CharField(choices=[('6PM', '6PM'), ('1PM', '1PM'), ('2PM', '2PM'), ('7AM', '7AM'), ('11AM', '11AM'), ('10AM', '10AM'), ('12NN', '12NN'), ('4PM', '4PM'), ('7PM', '7PM'), ('3PM', '3PM'), ('8PM', '8PM'), ('6AM', '6AM'), ('9PM', '9PM'), ('8AM', '8AM'), ('5PM', '5PM'), ('9AM', '9AM')], default='8AM', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Monday', 'Monday')], default='Monday', max_length=12),
        ),
    ]
