# Generated by Django 3.1.7 on 2021-08-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20210808_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.CharField(choices=[('1PM', '1PM'), ('7AM', '7AM'), ('12NN', '12NN'), ('6AM', '6AM'), ('2PM', '2PM'), ('3PM', '3PM'), ('4PM', '4PM'), ('5PM', '5PM'), ('6PM', '6PM'), ('9AM', '9AM'), ('7PM', '7PM'), ('9PM', '9PM'), ('8AM', '8AM'), ('8PM', '8PM'), ('11AM', '11AM'), ('10AM', '10AM')], default='5PM', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday')], default='Friday', max_length=12),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.CharField(choices=[('1PM', '1PM'), ('7AM', '7AM'), ('12NN', '12NN'), ('6AM', '6AM'), ('2PM', '2PM'), ('3PM', '3PM'), ('4PM', '4PM'), ('5PM', '5PM'), ('6PM', '6PM'), ('9AM', '9AM'), ('7PM', '7PM'), ('9PM', '9PM'), ('8AM', '8AM'), ('8PM', '8PM'), ('11AM', '11AM'), ('10AM', '10AM')], default='8AM', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday')], default='Monday', max_length=12),
        ),
    ]
