# Generated by Django 3.1.7 on 2021-08-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20210808_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.CharField(choices=[('7PM', '7PM'), ('6PM', '6PM'), ('8AM', '8AM'), ('3PM', '3PM'), ('8PM', '8PM'), ('6AM', '6AM'), ('5PM', '5PM'), ('9AM', '9AM'), ('4PM', '4PM'), ('1PM', '1PM'), ('9PM', '9PM'), ('10AM', '10AM'), ('11AM', '11AM'), ('12NN', '12NN'), ('7AM', '7AM'), ('2PM', '2PM')], default='5PM', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], default='Friday', max_length=12),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.CharField(choices=[('7PM', '7PM'), ('6PM', '6PM'), ('8AM', '8AM'), ('3PM', '3PM'), ('8PM', '8PM'), ('6AM', '6AM'), ('5PM', '5PM'), ('9AM', '9AM'), ('4PM', '4PM'), ('1PM', '1PM'), ('9PM', '9PM'), ('10AM', '10AM'), ('11AM', '11AM'), ('12NN', '12NN'), ('7AM', '7AM'), ('2PM', '2PM')], default='8AM', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], default='Monday', max_length=12),
        ),
    ]
