# Generated by Django 3.1.7 on 2021-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20210808_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.CharField(choices=[('2', '7AM'), ('7', '12NN'), ('4', '9AM'), ('1', '6AM'), ('3', '8AM'), ('13', '6PM'), ('5', '10AM'), ('16', '9PM'), ('15', '8PM'), ('9', '2PM'), ('10', '3PM'), ('6', '11AM'), ('11', '4PM'), ('8', '1PM'), ('14', '7PM'), ('12', '5PM')], default='12', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.CharField(choices=[('7', 'Sunday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('6', 'Saturday'), ('1', 'Monday'), ('5', 'Friday')], default='Friday', max_length=12),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.CharField(choices=[('2', '7AM'), ('7', '12NN'), ('4', '9AM'), ('1', '6AM'), ('3', '8AM'), ('13', '6PM'), ('5', '10AM'), ('16', '9PM'), ('15', '8PM'), ('9', '2PM'), ('10', '3PM'), ('6', '11AM'), ('11', '4PM'), ('8', '1PM'), ('14', '7PM'), ('12', '5PM')], default='3', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.CharField(choices=[('7', 'Sunday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('6', 'Saturday'), ('1', 'Monday'), ('5', 'Friday')], default='Monday', max_length=12),
        ),
    ]
