# Generated by Django 3.1.7 on 2021-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20210808_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.CharField(choices=[('14', '7PM'), ('9', '2PM'), ('16', '9PM'), ('3', '8AM'), ('15', '8PM'), ('8', '1PM'), ('12', '5PM'), ('13', '6PM'), ('5', '10AM'), ('11', '4PM'), ('1', '6AM'), ('7', '12NN'), ('10', '3PM'), ('2', '7AM'), ('6', '11AM'), ('4', '9AM')], default='12', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.CharField(choices=[('3', 'Wednesday'), ('5', 'Friday'), ('4', 'Thursday'), ('6', 'Saturday'), ('1', 'Monday'), ('7', 'Sunday'), ('2', 'Tuesday')], default='5', max_length=12),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.CharField(choices=[('14', '7PM'), ('9', '2PM'), ('16', '9PM'), ('3', '8AM'), ('15', '8PM'), ('8', '1PM'), ('12', '5PM'), ('13', '6PM'), ('5', '10AM'), ('11', '4PM'), ('1', '6AM'), ('7', '12NN'), ('10', '3PM'), ('2', '7AM'), ('6', '11AM'), ('4', '9AM')], default='3', max_length=4),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.CharField(choices=[('3', 'Wednesday'), ('5', 'Friday'), ('4', 'Thursday'), ('6', 'Saturday'), ('1', 'Monday'), ('7', 'Sunday'), ('2', 'Tuesday')], default='1', max_length=12),
        ),
    ]
