# Generated by Django 3.1.7 on 2021-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20210808_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.PositiveSmallIntegerField(choices=[('2', '7AM'), ('7', '12NN'), ('6', '11AM'), ('12', '5PM'), ('3', '8AM'), ('8', '1PM'), ('5', '10AM'), ('9', '2PM'), ('16', '9PM'), ('14', '7PM'), ('11', '4PM'), ('15', '8PM'), ('10', '3PM'), ('1', '6AM'), ('13', '6PM'), ('4', '9AM')], default='12'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.PositiveSmallIntegerField(choices=[('4', 'Thursday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('1', 'Monday'), ('5', 'Friday'), ('6', 'Saturday'), ('2', 'Tuesday')], default='5'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.PositiveSmallIntegerField(choices=[('2', '7AM'), ('7', '12NN'), ('6', '11AM'), ('12', '5PM'), ('3', '8AM'), ('8', '1PM'), ('5', '10AM'), ('9', '2PM'), ('16', '9PM'), ('14', '7PM'), ('11', '4PM'), ('15', '8PM'), ('10', '3PM'), ('1', '6AM'), ('13', '6PM'), ('4', '9AM')], default='3'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.PositiveSmallIntegerField(choices=[('4', 'Thursday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('1', 'Monday'), ('5', 'Friday'), ('6', 'Saturday'), ('2', 'Tuesday')], default='1'),
        ),
    ]
