# Generated by Django 3.1.7 on 2021-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20210808_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.PositiveSmallIntegerField(choices=[(6, '11AM'), (3, '8AM'), (14, '7PM'), (4, '9AM'), (13, '6PM'), (2, '7AM'), (16, '9PM'), (7, '12NN'), (15, '8PM'), (10, '3PM'), (1, '6AM'), (8, '1PM'), (9, '2PM'), (11, '4PM'), (12, '5PM'), (5, '10AM')], default='12'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (7, 'Sunday'), (2, 'Tuesday'), (6, 'Saturday'), (3, 'Wednesday'), (5, 'Friday'), (4, 'Thursday')], default='5'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.PositiveSmallIntegerField(choices=[(6, '11AM'), (3, '8AM'), (14, '7PM'), (4, '9AM'), (13, '6PM'), (2, '7AM'), (16, '9PM'), (7, '12NN'), (15, '8PM'), (10, '3PM'), (1, '6AM'), (8, '1PM'), (9, '2PM'), (11, '4PM'), (12, '5PM'), (5, '10AM')], default='3'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (7, 'Sunday'), (2, 'Tuesday'), (6, 'Saturday'), (3, 'Wednesday'), (5, 'Friday'), (4, 'Thursday')], default='1'),
        ),
    ]
