# Generated by Django 3.1.7 on 2021-08-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20210808_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.PositiveSmallIntegerField(choices=[(3, '8AM'), (15, '8PM'), (2, '7AM'), (12, '5PM'), (5, '10AM'), (13, '6PM'), (10, '3PM'), (11, '4PM'), (4, '9AM'), (1, '6AM'), (14, '7PM'), (6, '11AM'), (9, '2PM'), (16, '9PM'), (7, '12NN'), (8, '1PM')], default='12'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (3, 'Wednesday'), (4, 'Thursday'), (7, 'Sunday'), (2, 'Tuesday'), (5, 'Friday'), (6, 'Saturday')], default='5'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.PositiveSmallIntegerField(choices=[(3, '8AM'), (15, '8PM'), (2, '7AM'), (12, '5PM'), (5, '10AM'), (13, '6PM'), (10, '3PM'), (11, '4PM'), (4, '9AM'), (1, '6AM'), (14, '7PM'), (6, '11AM'), (9, '2PM'), (16, '9PM'), (7, '12NN'), (8, '1PM')], default='3'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (3, 'Wednesday'), (4, 'Thursday'), (7, 'Sunday'), (2, 'Tuesday'), (5, 'Friday'), (6, 'Saturday')], default='1'),
        ),
    ]
