# Generated by Django 3.1.7 on 2021-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20210808_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofficehours',
            name='closing',
            field=models.PositiveSmallIntegerField(choices=[(14, '7PM'), (5, '10AM'), (1, '6AM'), (9, '2PM'), (11, '4PM'), (12, '5PM'), (6, '11AM'), (13, '6PM'), (2, '7AM'), (8, '1PM'), (4, '9AM'), (7, '12NN'), (16, '9PM'), (10, '3PM'), (15, '8PM'), (3, '8AM')], default='12'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='last_day',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wednesday'), (7, 'Sunday'), (1, 'Monday'), (6, 'Saturday'), (5, 'Friday'), (2, 'Tuesday'), (4, 'Thursday')], default='5'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='opening',
            field=models.PositiveSmallIntegerField(choices=[(14, '7PM'), (5, '10AM'), (1, '6AM'), (9, '2PM'), (11, '4PM'), (12, '5PM'), (6, '11AM'), (13, '6PM'), (2, '7AM'), (8, '1PM'), (4, '9AM'), (7, '12NN'), (16, '9PM'), (10, '3PM'), (15, '8PM'), (3, '8AM')], default='3'),
        ),
        migrations.AlterField(
            model_name='schoolofficehours',
            name='starting_day',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wednesday'), (7, 'Sunday'), (1, 'Monday'), (6, 'Saturday'), (5, 'Friday'), (2, 'Tuesday'), (4, 'Thursday')], default='1'),
        ),
    ]
