# Generated by Django 3.1.7 on 2021-04-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to=models.Q(is_staff=True), on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staffprofile', serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('employee_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_registrar',
            field=models.BooleanField(default=False, verbose_name='Registrar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Teacher'),
        ),
    ]
