# Generated by Django 3.1.7 on 2021-04-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210402_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
    ]
