# Generated by Django 3.1.7 on 2021-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210402_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
