# Generated by Django 3.1.7 on 2021-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210402_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('Student', 'Student'), ('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Registrar', 'Registrar')], default='Student', max_length=15, verbose_name='User Role'),
        ),
    ]
