# Generated by Django 3.1.7 on 2021-04-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210422_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title_title',
            new_name='title',
        ),
    ]
