# Generated by Django 3.1.7 on 2021-04-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210422_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='author_title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='content_title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='title_title',
        ),
    ]
