# Generated by Django 3.1.7 on 2021-08-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210422_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
