# Generated by Django 3.1.7 on 2021-08-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_schoollogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=255)),
            ],
        ),
    ]
