# Generated by Django 3.1.7 on 2021-08-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsandannouncements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsandannouncements',
            options={'verbose_name_plural': 'News And Announcements'},
        ),
    ]
