# Generated by Django 3.1.7 on 2021-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsandannouncements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandannouncements',
            name='time_of_event',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
