# Generated by Django 3.1.7 on 2021-08-10 10:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_newsandannouncements_time_of_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=55)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('starting_verse', models.PositiveSmallIntegerField()),
                ('last_verse', models.PositiveSmallIntegerField(blank=True)),
                ('display_during', models.CharField(max_length=10)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
