# Generated by Django 3.1.7 on 2021-08-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_verseoftheday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verseoftheday',
            options={'verbose_name_plural': 'Verse of the Day'},
        ),
    ]
