# Generated by Django 3.1.7 on 2021-08-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210810_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseoftheday',
            name='last_verse',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
