# Generated by Django 3.1.7 on 2021-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210810_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseoftheday',
            name='display_during',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
    ]
