# Generated by Django 3.1.7 on 2021-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210810_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandannouncements',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsandannouncements',
            name='time_of_event',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
