# Generated by Django 3.1.7 on 2021-08-10 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210810_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateField()),
                ('time_of_event', models.TimeField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Upcoming Events',
            },
        ),
        migrations.DeleteModel(
            name='NewsAndAnnouncements',
        ),
    ]
