# Generated by Django 3.1.7 on 2021-08-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_announcements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Announcements'},
        ),
    ]
