# Generated by Django 3.1.7 on 2021-08-10 13:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210810_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_transferees', ckeditor.fields.RichTextField()),
                ('for_jr_hs', ckeditor.fields.RichTextField()),
                ('for_foreign_student', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Admission Requirements',
            },
        ),
    ]
