# Generated by Django 3.1.7 on 2021-08-10 14:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_admissionrequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', ckeditor.fields.RichTextField()),
                ('school_year', models.CharField(max_length=55)),
                ('tuition_content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Tuition Fees',
            },
        ),
    ]
