# Generated by Django 3.1.7 on 2021-08-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20210815_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(is_teacher=True), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
