# Generated by Django 3.1.7 on 2021-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210815_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='grade csv files')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('grades_uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
